### ISSUE TITLE
403 Client Error: Forbidden for url: https://replicate.com/api/models/stability-ai/sdxl/versions/2b017d9b67edd2ee1401238df49d75da53c523f36e363881e057f5dc3ed3c5b2/predictions

### ISSUE THREAD

**Issue by bacladjan-corp** [KoushikNavuluri/stable-diffusion-xl-api#1]
can you please tell how to fix error :
Error occurred while making the request: 403 Client Error: Forbidden for url: https://replicate.com/api/models/stability-ai/sdxl/versions/2b017d9b67edd2ee1401238df49d75da53c523f36e363881e057f5dc3ed3c5b2/predictions

**Comment by KoushikNavuluri** [comment]
If there are more no. of requests in a minute from a single ip, replicate bans ip temporarily. 
Make sure a maintain a timeout or use proxies.

**Comment by bacladjan-corp** [comment]
thanks

**Comment by KoushikNavuluri** [comment]
Please give a star if you like , and follow and support for such projects ! 🤗 👬

**Comment by vacerde** [comment]
How long is a temp ban?
